### ISSUE TITLE
Mpx(1005)

### ISSUE THREAD

**Issue by DWYW** [pagnkelly/vscode-mpx#11]
![image](https://user-images.githubusercontent.com/19439805/78125550-c54cd880-7443-11ea-9ad4-bcc058d542dd.png)

**Comment by pagnkelly** [comment]
最新版本吗？最新版本修复了此问题

**Comment by DWYW** [comment]
vscode 
版本: 1.43.2
提交: 0ba0ca52957102ca3527cf479571617f0de6ed50
日期: 2020-03-24T07:34:57.037Z
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

mpx: 0.1.7

**Comment by pagnkelly** [comment]
能把代码提供下吗

**Comment by DWYW** [comment]
今天自己就好了，感谢解答
